goinvest/iexcloud

- client.go
This should fix https://github.com/goinvest/iexcloud/issues/13
> Added error reporting for invalid token

- account.go
- examples/iexcloud/cmd/account.go
- helpers.go
Fixes https://github.com/goinvest/iexcloud/issues/18; also added an example so I could test easily.
> Fix account metadata unmarshalling issue

- client.go
- helpers.go
Minor fixes to a type-o and a cut+paste error in endpoints.
> Minor fixups

- README.md
- client.go
- examples/iexcloud/cmd/deep.go
- iexdata.go
- stocks.go
Addition of the top-level DEEP endpoint as well as the book and trades endpoints.
Added deep, deep-book, deep-trades to the CLI.
> DEEP endpoint support

- README.md
- client.go
- examples/iexcloud/cmd/client.go
- examples/iexcloud/cmd/collections.go
- examples/iexcloud/cmd/deep.go
- examples/iexcloud/cmd/sectors.go
- examples/iexcloud/cmd/symbols.go
- examples/iexcloud/cmd/tags.go
- helpers.go
- iexdata.go
- refdata.go
- stocks.go
Added support for sector and tag collections.
Minor fixup to JSON EpochTime parsing.
Fixups for comments and other code style infractions raised by 'make check'.
> Add support for sector and tag collections

- client.go
> Add HTTP Client option

- client.go
- examples/iexcloud/cmd/account.go
- examples/iexcloud/cmd/balancesheets.go
- examples/iexcloud/cmd/client.go
- examples/iexcloud/cmd/collections.go
- examples/iexcloud/cmd/company.go
- examples/iexcloud/cmd/deep.go
- examples/iexcloud/cmd/delayedquote.go
- examples/iexcloud/cmd/dividends.go
- examples/iexcloud/cmd/earnings.go
- examples/iexcloud/cmd/estimates.go
- examples/iexcloud/cmd/financials.go
- examples/iexcloud/cmd/historical.go
- examples/iexcloud/cmd/mostactive.go
- examples/iexcloud/cmd/peers.go
- examples/iexcloud/cmd/price.go
- examples/iexcloud/cmd/quote.go
- examples/iexcloud/cmd/sectors.go
- examples/iexcloud/cmd/stats.go
- examples/iexcloud/cmd/status.go
- examples/iexcloud/cmd/symbols.go
- examples/iexcloud/cmd/tags.go
- examples/iexcloud/main.go
- go.mod
- go.sum
Sponsored-by: BackendBenchmarking (backendb.com)
> Make all calls context-aware.

- refdata.go
Sponsored-by: BackendBenchmarking (backendb.com)
> Add missing fields to USExchange struct

- client.go
Sponsored-by: BackendBenchmarking (backendb.com)
Fixes #31
> Fix NextHoliday & NextHolidays return types

- helpers.go
- stocks.go
* Change IssueType to string, helpers exist to convert back to IssueType if required
Sponsored-by: BackendBenchmarking (backendb.com)
Also merge in #36 to v2 branch
> Update Company struct with additional fields

- client.go
> Typo in client.go

- .gitignore
- README.md
- client.go
- examples/iexcloud/cmd/ipostoday.go
- examples/iexcloud/cmd/upcoming.go
- marketinfo.go
- stockfundamentals.go
- stockresearch.go
Added support for upcoming events.
Added support for today's IPOs.
Added missing fields to Estimate.
> Added support for upcoming events and today's IPOs

- .gitignore
- README.md
- client.go
- examples/iexcloud/cmd/ipostoday.go
- examples/iexcloud/cmd/upcoming.go
- marketinfo.go
- stockfundamentals.go
- stockresearch.go
Added better error messages for non-normal status codes.
This change should be merged after my pull request #55, since those changes are present here.
> Added better error messages for non-normal status codes.

- client.go
> client: introduce package level Error type and use it for API HTTP errors

- client.go
- historical.go
> Add IntradayPricesWithOpts and intraday options struct

- altdata.go
- client.go
- cryptocurrency.go
Create a separate file for cryptocurrency and add corresponding endpoints based on https://iexcloud.io/docs/api/#cryptocurrency.
> Cryptocurrency - add price, books and move quote

- stockfundamentals.go
Added/Updated Earning struct fields based on https://iexcloud.io/docs/api/#earnings
> Earning Struct - Add, update and re-order fields

- stockfundamentals.go
They're sending dividends amount as a float starting 1st of December. This PR effectively reverts the one submitted to #41 previously
> Corrected dividends amount struct tag

- client.go
Add Previous Day Batch support.
> Add Previous Day Batch support

- client.go
- refdata.go
This endpoint searches stock symbols by fragment.
> Add a "search" command.

- client_test.go
This catches the error fixed by https://github.com/goinvest/iexcloud/pull/95
to prevent future regressions.
> Added a test for the URL generate method.

- client.go
- client_test.go
I also refactored the lib slightly to make testing easier, in a
backwards-compatible way so it shouldn't affect anyone.
> Add a unit test for income statements (quarterly and annual).

- .github/workflows/go.yml
We'll need to add more tests to make this more useful, but running the unit tests and making sure they work is a big first step. I already validated this works in my own fork of the repository.
This yaml file was automatically generated by GitHub in the "Actions" section because there is a template for Go projects, but it can easily be expanded on to include more checks.
> Add basic build/test workflow for validating PRs
